SchoolProjectS6/PFES6/urls.py
from django.urls import path

from . import views
app_name = 'PFES6'
urlpatterns = [
    path('', views.index, name='index'),
    path('teacher', views.teacher_index, name="teacher"),
    path('profileT', views.profileT, name='profileT'),
    path('displayData', views.displayData, name='displayData'),
    path('updatingData', views.updatingData, name='updatingData'),
    path('addCourseSubject', views.addCourseSubject, name='addCourseSubject'),
    path('addCourse', views.addCourse, name='addCourse'),
    path('allCourses', views.allCourses, name='allCourses'),
    path('formUploadC', views.formUploadC, name='formUploadC'),
    path('addingCourse', views.addingCourse, name='addingCourse'),
    path('deleteCourse', views.deleteCourse, name='deleteCourse'),
    path('displayCourseDetails', views.displayCourseDetails,
         name='displayCourseDetails'),
    path('formUploadTD', views.formUploadTD, name='formUploadTD'),
    path('addingTD', views.addingTD, name='addingTD'),
    path('formUploadTP', views.formUploadTP, name='formUploadTP'),
    path('addingTP', views.addingTP, name='addingTP'),
    path('formUploadCorre', views.formUploadCorre, name='formUploadCorre'),
    path('addingCorr', views.addingCorr, name='addingCorr'),
    path('deleteCourseFile', views.deleteCourseFile, name='deleteCourseFile'),
    path('deleteTD', views.deleteTD, name='deleteTD'),
    path('deleteTP', views.deleteTP, name='deleteTP'),
    path('deleteCorr', views.deleteCorr, name='deleteCorr'),
    path('formUploadHW', views.formUploadHW, name='formUploadHW'),
    path('sendingHW', views.sendingHW, name='sendingHW'),
    path('displayAllStudents', views.displayAllStudents, name='displayAllStudents'),
    path('statistics', views.statistics, name='statistics'),
    path('student', views.student_index, name='student'),
    path('student/course', views.student_course, name='student_course'),
    path('student/join_course', views.student_join_course,
         name='student_join_course'),
    path('student/to_do', views.student_to_do, name='student_to_do'),
    path('student/profile', views.student_profile, name='student_profile'),
    path('student/edit_picture', views.student_picture, name='student_picture'),
    path('student/put_todo', views.student_put_todo, name='student_put_todo'),
    path('student/edit_profile', views.student_edit_profile,
         name='student_edit_profile'),
    path('student/delete_course', views.destroy,
         name='destroy'),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name='logout'),

]

SchoolProjectS6/SchoolProjectS6/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from  django.conf.urls.static import static


urlpatterns = [
    path('', include('PFES6.urls')),
    path('admin/', admin.site.urls),
    
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

SchoolProjectS6/SchoolProjectS6/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href="{% static 'homepage/css/styles.css' %}">

</head>
<body>

<!-- header section starts  -->

<header>

    <a href="#home" class="logo"><span>Home</span>Page</a>

    <input type="checkbox" id="menu-bar">
    <label for="menu-bar" class="fas fa-bars"></label>

    <nav class="navbar">
        <a href="#home">home</a>
        <a href="#features">features</a>
        <a href="#about">about</a>
        <a class="btn" style="color: #fff;" onclick="openForm()">Log In</a>
    </nav>

</header>

<!-- header section ends -->

<!-- home section starts  -->

<section class="home" id="home">

    <div class="content">
        <h3>online class <span>management</span></h3>
        <p>Get more time to teach and inspire learners with Classroom.</p>
        <a href="#" class="btn" onclick="openForm()">Login</a>
    </div>

    <div class="image">
        <img src="{% static 'homepage/images/home-img.png' %}" alt="">
    </div>

</section>

<!-- home section ends -->

<!-- features section starts  -->

<section class="features" id="features">

    <h1 class="heading"> features </h1>

    <div class="box-container">

        <div class="box">
            <img src="{% static 'homepage/images/manage.svg' %}" alt="">
            <h3>MANAGE</h3>
            <p>Simplify teaching and learning</p>
            <a class="btn">read more</a>
        </div>

        <div class="box">
            <img src="{% static 'homepage/images/measure.svg' %}" alt="">
            <h3>MEASURE</h3>
            <p>Move students forward</p>
            <a class="btn">read more</a>
        </div>

        <div class="box">
            <img src="{% static 'homepage/images/collaborate.svg' %}" alt="">
            <h3>COLLABORATE</h3>
            <p>Strengthen student connections</p>
            <a class="btn">read more</a>
        </div>

    </div>

</section>

<!-- features section ends -->

<!-- about section starts  -->

<section class="about" id="about">

    <h1 class="heading"> about </h1>

    <div class="column">

        <div class="image">
            <img src="{% static 'homepage/images/about.svg' %}" alt="">
        </div>

        <div class="content">
            <h3>Easy And Perfect Solution For Your Online Class Management</h3>
            <p>Get it as part of Workspace for Education</p>
            <p>If you’re using it in school, we recommend signing up for Education Workspace. It is already included in Workspace for Education and works seamlessly with Workspace collaboration tools.</p>
        </div>

    </div>

</section>

<!-- about section ends -->

<!-- footer section starts  -->

<div class="footer">

    <div class="box-container">

        <div class="box">
            <h3>about us</h3>
            <p>A free and easy tool helping educators efficiently manage and assess progress, while enhancing connections with learners from school, from home, or on the go.</p>
        </div>

        <div class="box">
            <h3>quick links</h3>
            <a href="#home">home</a>
            <a href="#features">features</a>
            <a href="#about">about</a>
        </div>

        <div class="box">
            <h3>follow us</h3>
            <a href="">Linkedin</a>
            <a href="">Github</a>
        </div>

        <div class="box">
            <h3>contact info</h3>
            <div class="info">
                <i class="fas fa-phone"></i>
                <p> +212 601-409071 <br> +212 613-357700 </p>
            </div>
            <div class="info">
                <i class="fas fa-envelope"></i>
                <p> hajar.aitabdielmomin@uit.ac.ma <br> houssam.mrabet@uit.ac.ma </p>
            </div>
        </div>

    </div>

    <h1 class="credit"> &copy; copyright - 2021</h1>

</div>

<!-- footer section ends -->

<div class="full-container">
    <div class="popup-container">
        <label class="close-btn fas fa-times" onclick="closeForm()"></label>
        <div class="text">Login</div>

            
<form action="{% url 'PFES6:login' %}" method="POST">
    {% csrf_token %}
    <div class="data">
        <label>Email</label>
        <input type="email" name="email" required>
    </div>
    <div class="data">
        <label>Password</label>
        <input type="password" name="password" required>
</div>
        
            <div class="btn-p">
                <div class="inner"></div>
                <button type="submit" value="login">Login</button>
            </div>
        </form>
    </div>
</div>

<script src="{% static 'homepage/js/app.js' %}"></script>

</body>
</html>