SchoolProjectS6/PFES6/urls.py
from django.urls import path

from . import views
app_name = 'PFES6'
urlpatterns = [
    path('', views.index, name='index'),
    path('teacher', views.teacher_index, name="teacher"),
    path('profileT', views.profileT, name='profileT'),
    path('displayData', views.displayData, name='displayData'),
    path('updatingData', views.updatingData, name='updatingData'),
    path('addCourseSubject', views.addCourseSubject, name='addCourseSubject'),
    path('addCourse', views.addCourse, name='addCourse'),
    path('allCourses', views.allCourses, name='allCourses'),
    path('formUploadC', views.formUploadC, name='formUploadC'),
    path('addingCourse', views.addingCourse, name='addingCourse'),
    path('deleteCourse', views.deleteCourse, name='deleteCourse'),
    path('displayCourseDetails', views.displayCourseDetails,
         name='displayCourseDetails'),
    path('formUploadTD', views.formUploadTD, name='formUploadTD'),
    path('addingTD', views.addingTD, name='addingTD'),
    path('formUploadTP', views.formUploadTP, name='formUploadTP'),
    path('addingTP', views.addingTP, name='addingTP'),
    path('formUploadCorre', views.formUploadCorre, name='formUploadCorre'),
    path('addingCorr', views.addingCorr, name='addingCorr'),
    path('deleteCourseFile', views.deleteCourseFile, name='deleteCourseFile'),
    path('deleteTD', views.deleteTD, name='deleteTD'),
    path('deleteTP', views.deleteTP, name='deleteTP'),
    path('deleteCorr', views.deleteCorr, name='deleteCorr'),
    path('formUploadHW', views.formUploadHW, name='formUploadHW'),
    path('sendingHW', views.sendingHW, name='sendingHW'),
    path('displayAllStudents', views.displayAllStudents, name='displayAllStudents'),
    path('statistics', views.statistics, name='statistics'),
    path('student', views.student_index, name='student'),
    path('student/course', views.student_course, name='student_course'),
    path('student/join_course', views.student_join_course,
         name='student_join_course'),
    path('student/to_do', views.student_to_do, name='student_to_do'),
    path('student/profile', views.student_profile, name='student_profile'),
    path('student/edit_picture', views.student_picture, name='student_picture'),
    path('student/put_todo', views.student_put_todo, name='student_put_todo'),
    path('student/edit_profile', views.student_edit_profile,
         name='student_edit_profile'),
    path('student/delete_course', views.destroy,
         name='destroy'),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name='logout'),

]

SchoolProjectS6/SchoolProjectS6/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from  django.conf.urls.static import static


urlpatterns = [
    path('', include('PFES6.urls')),
    path('admin/', admin.site.urls),
    
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

SchoolProjectS6/SchoolProjectS6/templates/Teacher/allCourses.html
{% extends "Teacher/base.html" %}
{% load static %}
{% block cssD %}
<style>
  .card {
cursor: pointer;
transition: all 0.5s;
}

.card:hover {
transform: scale(1.05);
}
</style>

{% endblock %}

{% block content %}
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Courses</h1>
          </div>

          <div class="row mb-3">
         
           <div class="col-xl-3 col-md-6 mb-4">
             <div class="card h-100">
                <div style="margin: auto;">
				 <a href="{% url 'PFES6:addCourseSubject' %}?uId={{user.id}}"> 
                  <i class="fas fa-plus fa-5x"></i>
				  </a>
                </div>
              </div>
            </div> 
          {% for c in classe %}
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card h-100">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
					<a href="{% url 'PFES6:displayCourseDetails' %}?uId={{user.id}}&idC={{ c.id }}">
                      <div class="h5 mb-0 font-weight-bold text-gray-800">{{ c.titleClass }}</div>
                      <div class=" mb-1">{{ c.level }} <br> {{ c.creationDateClasse }}</div>
					   </a>
                     <a href="{% url 'PFES6:deleteCourse' %}?uId={{user.id}}&idC={{ c.id }}"> <div class="mt-2 mb-0 text-muted text-xs">Remove this course</div></a>
					 
                    </div>
                    <div class="col-auto" style="align-self: flex-start;">
                      <img class="img-profile rounded-circle" src="{{ user.picture.url}}" width="58px" height="58px" alt="">
					  <div class="mt-2 mb-0 text-muted text-xs">{{user.nom}} {{user.prenom}}</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
           {% endfor %}
           
          </div>
{% endblock %}
{% block sidebar %}
<ul class="navbar-nav sidebar sidebar-light accordion" id="accordionSidebar">
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'PFES6:statistics' %}?uId={{user.id}}">
    <div class="sidebar-brand-icon">
      Online Class
    </div>
    <div class="sidebar-brand-text mx-3"></div>
  </a>
  <hr class="sidebar-divider my-0">
 <br>
  <div class="sidebar-heading">
    Actions
  </div>
 <li class="nav-item">
    <a class="nav-link " href="{% url 'PFES6:statistics' %}?uId={{user.id}}">
      <i class="fas fa-fw fa-home"></i>
      <span>Home</span>
    </a>
  </li>
 <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:addCourseSubject' %}?uId={{user.id}}">
      <i class="fas fa-book-open"></i>
      <span>Add course</span>
    </a>
  </li>
 <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:formUploadC' %}?uId={{user.id}}">
      <i class="fas fa-file-pdf"></i>
      <span>Upload course</span>
    </a>
  </li>
 <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:formUploadTD' %}?uId={{user.id}}">
      <i class="fas fa-file-pdf"></i>
      <span>Upload TD</span>
    </a>
  </li>
 <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:formUploadTP' %}?uId={{user.id}}">
      <i class="fas fa-file-pdf"></i>
      <span>Upload TP</span>
    </a>
  </li>
 <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:formUploadCorre' %}?uId={{user.id}}">
      <i class="fas fa-file-pdf"></i>
      <span>Upload correction</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:formUploadHW' %}?uId={{user.id}}">
      <i class="fas fa-file-pdf"></i>
      <span>Send homeWork</span>
    </a>
  </li>
 
 
  <hr class="sidebar-divider">
  <div class="sidebar-heading">
    Views
  </div>
  <li class="nav-item active">
   <a class="nav-link" href="{% url 'PFES6:allCourses' %}?idUs={{user.id}}">
      <i class="fas fa-fw fa-book"></i>
      <span>Yous courses</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseBootstrap"
      aria-expanded="true" aria-controls="collapseBootstrap">
      <i class="fas fa-fw fa-users"></i>
      <span>Your students</span>
    </a>
    <div id="collapseBootstrap" class="collapse" aria-labelledby="headingBootstrap" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        {% for c in classeS %}
        <a class="collapse-item" href="{% url 'PFES6:displayAllStudents' %}?uId={{user.id}}&idC={{c.id}}">{{c.titleClass}}</a>
        {% endfor %}
      </div>
    </div>
  </li>
  
</ul>

{% endblock %}
         

SchoolProjectS6/SchoolProjectS6/templates/Teacher/courseDetails.html
{% extends "Teacher/base.html" %}
} 
{% block content %}
          <div class="row" >
                 <div class="col-lg-12 mb-4">
              <!-- Simple Tables -->
              <div class="card">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Courses File</h6>
                </div>
                <div class="table-responsive">
                  <table class="table align-items-center table-flush">
                    <thead class="thead-light">
                      <tr>
                        <th>Title</th>
                        <th>Date of creation</th>
                        <th>File to download</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                     
                     {% for c in courses %}
                      <tr>
                        <td>{{ c.desc }}</td>
                        <td>{{ c.creationDateCourse }}</td>
                        <td><a href="{{ c.courseFile.url }}" download>{{ c.courseFile }}</a></td>
                        <td><a href="{% url 'PFES6:deleteCourseFile' %}?uId={{user.id}}&idC={{ classe.id }}&idFileC={{ c.id }}" class="btn btn-sm btn-primary">Delete</a></td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
                <div class="card-footer"></div>
              </div>
            </div>
<br><br>

      <div class="col-lg-12 mb-4">
              <!-- Simple Tables -->
              <div class="card">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">TD Files</h6>
                </div>
                <div class="table-responsive">
                  <table class="table align-items-center table-flush">
                    <thead class="thead-light">
                      <tr>
                        <th>Title</th>
                        <th>Date of creation</th>
                        <th>File to download</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                     
                     
                      {% for td in tdFiles %}
                      <tr>
                        <td>{{ td.titleTd }}</td>
                        <td>{{ td.creationDateTd }}</td>
                        <td><a href="{{ td.tdFile.url }}" download>{{ td.tdFile }}</a></td>
                        <td><a href="{% url 'PFES6:deleteTD' %}?uId={{user.id}}&idC={{ classe.id }}&idFileTD={{ td.id }}" class="btn btn-sm btn-primary">Delete</a></td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
                <div class="card-footer"></div>
              </div>
            </div>
           
            <br><br>
		   <div class="col-lg-12 mb-4">
              <!-- Simple Tables -->
              <div class="card">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">TP Files</h6>
                </div>
                <div class="table-responsive">
                  <table class="table align-items-center table-flush">
                    <thead class="thead-light">
                      <tr>
                        <th>Title</th>
                        <th>Date of creation</th>
                        <th>File to download</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                     
                      {% for tp in tpFiles %}
                      <tr>
                        <td>{{ tp.titleTp }}</td>
                        <td>{{ tp.creationDateTp }}</td>
                        <td><a href="{{ tp.tpFile.url }}" download>{{ tp.tpFile }}</a></td>
                        <td><a href="{% url 'PFES6:deleteTP' %}?uId={{user.id}}&idC={{ classe.id }}&idFileTP={{ tp.id }}" class="btn btn-sm btn-primary">Delete</a></td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
                <div class="card-footer"></div>
              </div>
            </div>
			
            <br><br>
			<div class="col-lg-12 mb-4">
              <!-- Simple Tables -->
              <div class="card">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Correction File</h6>
                </div>
                <div class="table-responsive">
                  <table class="table align-items-center table-flush">
                    <thead class="thead-light">
                      <tr>
                        <th>Title</th>
                        <th>Date of creation</th>
                        <th>File to download</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                     
                     
                      {% for corr in corrFiles %}
                      <tr>
                        <td>{{ corr.title }}</td>
                        <td>{{ corr.creationDateTdTp }}</td>
                        <td><a href="{{ corr.corrFile.url }}" download>{{ corr.corrFile }}</a></td>
                        <td><a href="{% url 'PFES6:deleteCorr' %}?uId={{user.id}}&idC={{ classe.id }}&idFileCorr={{ corr.id }}" class="btn btn-sm btn-primary">Delete</a></td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
                <div class="card-footer"></div>
              </div>
            </div>
            <br><br>
		   <div class="col-lg-12 mb-4">
              
              <div class="card">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Home Work Files</h6>
                </div>
                <div class="table-responsive">
                  <table class="table align-items-center table-flush">
                    <thead class="thead-light">
                      <tr>
                        <th>title</th>
                        <th>Date of creation</th>
                        <th>Homework file todo</th>
                        <th>Student's homework</th>
                      </tr>
                    </thead>
                    <tbody>
                     
                      
                {% for hm in homeWorks %}  
                    {% if hm.TodoSFile == '' %}

                    {% else %}
                     <tr>
                      <td>{{ hm.title }}</td>
                      <td>{{ hm.creationDateTodo }}</td>
                      <td><a href="{{ hm.TodoTFile.url }}" download>{{ hm.TodoTFile }}</a></td>
                      <td><a href="{{ hm.TodoSFile.url }}" download>{{ hm.TodoSFile }}</a></td>
                    </tr>
                    {% endif %}
                {% endfor %}
                    </tbody>
                  </table>
                </div>
                <div class="card-footer"></div>
              </div>
            </div>
          </div>
 {% endblock %}
 {% block sidebar %}
 <ul class="navbar-nav sidebar sidebar-light accordion" id="accordionSidebar">
   <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'PFES6:statistics' %}?uId={{user.id}}">
     <div class="sidebar-brand-icon">
       Online Class
     </div>
     <div class="sidebar-brand-text mx-3"></div>
   </a>
   <hr class="sidebar-divider my-0">
  <br>
   <div class="sidebar-heading">
     Actions
   </div>
  <li class="nav-item">
     <a class="nav-link " href="{% url 'PFES6:statistics' %}?uId={{user.id}}">
       <i class="fas fa-fw fa-home"></i>
       <span>Home</span>
     </a>
   </li>
  <li class="nav-item">
     <a class="nav-link" href="{% url 'PFES6:addCourseSubject' %}?uId={{user.id}}">
       <i class="fas fa-book-open"></i>
       <span>Add course</span>
     </a>
   </li>
  <li class="nav-item">
     <a class="nav-link" href="{% url 'PFES6:formUploadC' %}?uId={{user.id}}">
       <i class="fas fa-file-pdf"></i>
       <span>Upload course</span>
     </a>
   </li>
  <li class="nav-item">
     <a class="nav-link" href="{% url 'PFES6:formUploadTD' %}?uId={{user.id}}">
       <i class="fas fa-file-pdf"></i>
       <span>Upload TD</span>
     </a>
   </li>
  <li class="nav-item">
     <a class="nav-link" href="{% url 'PFES6:formUploadTP' %}?uId={{user.id}}">
       <i class="fas fa-file-pdf"></i>
       <span>Upload TP</span>
     </a>
   </li>
  <li class="nav-item">
     <a class="nav-link" href="{% url 'PFES6:formUploadCorre' %}?uId={{user.id}}">
       <i class="fas fa-file-pdf"></i>
       <span>Upload correction</span>
     </a>
   </li>
   <li class="nav-item">
     <a class="nav-link" href="{% url 'PFES6:formUploadHW' %}?uId={{user.id}}">
       <i class="fas fa-file-pdf"></i>
       <span>Send homeWork</span>
     </a>
   </li>
  
  
   <hr class="sidebar-divider">
   <div class="sidebar-heading">
     Views
   </div>
   <li class="nav-item active">
    <a class="nav-link" href="{% url 'PFES6:allCourses' %}?idUs={{user.id}}">
       <i class="fas fa-fw fa-book"></i>
       <span>Yous courses</span>
     </a>
   </li>
   <li class="nav-item">
     <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseBootstrap"
       aria-expanded="true" aria-controls="collapseBootstrap">
       <i class="fas fa-fw fa-users"></i>
       <span>Your students</span>
     </a>
     <div id="collapseBootstrap" class="collapse" aria-labelledby="headingBootstrap" data-parent="#accordionSidebar">
       <div class="bg-white py-2 collapse-inner rounded">
         {% for c in classeS %}
         <a class="collapse-item" href="{% url 'PFES6:displayAllStudents' %}?uId={{user.id}}&idC={{c.id}}">{{c.titleClass}}</a>
         {% endfor %}
       </div>
     </div>
   </li>
   
 </ul>
 
 {% endblock %}
          

SchoolProjectS6/SchoolProjectS6/templates/Teacher/formAddCourse.html
{% extends "Teacher/base.html" %}


{% block content %}
          <div class="row" >
            <div class="col-lg-6" style="margin-left : 20%;">
       
              <div class="card mb-4" >
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Add a course</h6>
                </div>
                <div class="card-body" >
                  <form method="POST" action="{% url 'PFES6:addCourse' %}">{% csrf_token %}
                    <input type="hidden" name="idus" value="{{ user.id }}">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Title </label>
                      <input type="text" class="form-control" name="titleC" id="exampleInputEmail1" aria-describedby="emailHelp"
                        placeholder="Course name" required>
    
                    </div>
					 <div class="form-group">
                      <label for="exampleInputEmail1">Level </label>
                      <input type="text" class="form-control" name="levelC" id="exampleInputEmail1" aria-describedby="emailHelp"
                        placeholder="example : SMI S2" required>
    
                    </div>
                    <div class="form-group">
                      <label for="exampleInputPassword1">Code</label>
                      <input type="text" class="form-control" id="exampleInputPassword1" name="codeC" placeholder="Code for your course" required>
                    </div>
					  
        
                
                    <input type="submit" class="btn btn-primary" value="Add" name="send">
					<input type="reset" value="Clear" name="clear" class="btn btn-default">
                  </form>
                </div>
              </div>

             

            </div>

            <div class="col-lg-6">
            

            </div>
          </div>
{% endblock %}
{% block sidebar %}
<ul class="navbar-nav sidebar sidebar-light accordion" id="accordionSidebar">
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'PFES6:statistics' %}?uId={{user.id}}">
    <div class="sidebar-brand-icon">
      Online Class
    </div>
    <div class="sidebar-brand-text mx-3"></div>
  </a>
  <hr class="sidebar-divider my-0">
 <br>
  <div class="sidebar-heading">
    Actions
  </div>
 <li class="nav-item">
    <a class="nav-link " href="{% url 'PFES6:statistics' %}?uId={{user.id}}">
      <i class="fas fa-fw fa-home"></i>
      <span>Home</span>
    </a>
  </li>
 <li class="nav-item active">
    <a class="nav-link" href="{% url 'PFES6:addCourseSubject' %}?uId={{user.id}}">
      <i class="fas fa-book-open"></i>
      <span>Add course</span>
    </a>
  </li>
 <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:formUploadC' %}?uId={{user.id}}">
      <i class="fas fa-file-pdf"></i>
      <span>Upload course</span>
    </a>
  </li>
 <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:formUploadTD' %}?uId={{user.id}}">
      <i class="fas fa-file-pdf"></i>
      <span>Upload TD</span>
    </a>
  </li>
 <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:formUploadTP' %}?uId={{user.id}}">
      <i class="fas fa-file-pdf"></i>
      <span>Upload TP</span>
    </a>
  </li>
 <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:formUploadCorre' %}?uId={{user.id}}">
      <i class="fas fa-file-pdf"></i>
      <span>Upload correction</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:formUploadHW' %}?uId={{user.id}}">
      <i class="fas fa-file-pdf"></i>
      <span>Send homeWork</span>
    </a>
  </li>
 
 
  <hr class="sidebar-divider">
  <div class="sidebar-heading">
    Views
  </div>
  <li class="nav-item">
   <a class="nav-link" href="{% url 'PFES6:allCourses' %}?idUs={{user.id}}">
      <i class="fas fa-fw fa-book"></i>
      <span>Yous courses</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseBootstrap"
      aria-expanded="true" aria-controls="collapseBootstrap">
      <i class="fas fa-fw fa-users"></i>
      <span>Your students</span>
    </a>
    <div id="collapseBootstrap" class="collapse" aria-labelledby="headingBootstrap" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        {% for c in classeS %}
        <a class="collapse-item" href="{% url 'PFES6:displayAllStudents' %}?uId={{user.id}}&idC={{c.id}}">{{c.titleClass}}</a>
        {% endfor %}
      </div>
    </div>
  </li>
  
</ul>

{% endblock %}

SchoolProjectS6/SchoolProjectS6/templates/Teacher/formUpdateData.html
{% extends "Teacher/base.html" %}
 
{% block content %}
          <div class="row" >
            <div class="col-lg-6" style="margin-left : 20%;">
           
              <div class="card mb-4" >
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Update your data</h6>
                </div>
                <div class="card-body" >
                  <form method="POST" action="{% url 'PFES6:updatingData' %}" enctype="multipart/form-data">{% csrf_token %}
                    <input type="hidden" name="idUser" value="{{user.id}}">
                    <input type="hidden" name="role" value="{{user.role}}">
                    <div class="form-group">
               
                      <input type="text" class="form-control" name="FN" id="exampleInputEmail1" aria-describedby="emailHelp"
                        value="{{ user.prenom }}" required>
    
                    </div>
				
                <div class="form-group">
             
                      <input type="text" class="form-control" name="LN" id="exampleInputEmail1" aria-describedby="emailHelp"
                        value="{{ user.nom }}" required>
    
                    </div>
               <div class="form-group">
   
                      <input type="email" class="form-control" name="email" id="exampleInputEmail1" aria-describedby="emailHelp"
                        value="{{ user.email }}" required>
    
                    </div>
					<div class="form-group">
             
                      <input type="password" class="form-control" name="psw" id="exampleInputEmail1" aria-describedby="emailHelp"
                        value="{{ user.password }}" required>
                    </div>
					  <div class="form-group">
                      <div class="custom-file">
                     
                        <input type="file" class="custom-file-input" id="customFile" name="fileImgUpdate">
                        <label class="custom-file-label" for="customFile">Choose Photo</label>
                      </div>
                    </div> 
                    <input type="submit" class="btn btn-primary" value="Update" name="sendNewData">
					<input type="reset" value="Clear" id="clear" class="btn btn-default">
                  </form>
                </div>
              </div>

            

            </div>

            <div class="col-lg-6">
            

            </div>
          </div>
 {% endblock %}
 {% block jsLinks %}
  
     
 <script>
  $('#customFile').on('change',function(){
      //get the file name
      var fileName = $(this).val().replace('C:\\fakepath\\', " ");
      //replace the "Choose a file" label
      $(this).next('.custom-file-label').html(fileName);	
  })



</script>
{% endblock %} 
{% block sidebar %}
<ul class="navbar-nav sidebar sidebar-light accordion" id="accordionSidebar">
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'PFES6:statistics' %}?uId={{user.id}}">
    <div class="sidebar-brand-icon">
      Online Class
    </div>
    <div class="sidebar-brand-text mx-3"></div>
  </a>
  <hr class="sidebar-divider my-0">
 <br>
  <div class="sidebar-heading">
    Actions
  </div>
 <li class="nav-item">
    <a class="nav-link " href="{% url 'PFES6:statistics' %}?uId={{user.id}}">
      <i class="fas fa-fw fa-home"></i>
      <span>Home</span>
    </a>
  </li>
 <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:addCourseSubject' %}?uId={{user.id}}">
      <i class="fas fa-book-open"></i>
      <span>Add course</span>
    </a>
  </li>
 <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:formUploadC' %}?uId={{user.id}}">
      <i class="fas fa-file-pdf"></i>
      <span>Upload course</span>
    </a>
  </li>
 <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:formUploadTD' %}?uId={{user.id}}">
      <i class="fas fa-file-pdf"></i>
      <span>Upload TD</span>
    </a>
  </li>
 <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:formUploadTP' %}?uId={{user.id}}">
      <i class="fas fa-file-pdf"></i>
      <span>Upload TP</span>
    </a>
  </li>
 <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:formUploadCorre' %}?uId={{user.id}}">
      <i class="fas fa-file-pdf"></i>
      <span>Upload correction</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:formUploadHW' %}?uId={{user.id}}">
      <i class="fas fa-file-pdf"></i>
      <span>Send homeWork</span>
    </a>
  </li>
 
 
  <hr class="sidebar-divider">
  <div class="sidebar-heading">
    Views
  </div>
  <li class="nav-item">
   <a class="nav-link" href="{% url 'PFES6:allCourses' %}?idUs={{user.id}}">
      <i class="fas fa-fw fa-book"></i>
      <span>Yous courses</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseBootstrap"
      aria-expanded="true" aria-controls="collapseBootstrap">
      <i class="fas fa-fw fa-users"></i>
      <span>Your students</span>
    </a>
    <div id="collapseBootstrap" class="collapse" aria-labelledby="headingBootstrap" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        {% for c in classeS %}
        <a class="collapse-item" href="{% url 'PFES6:displayAllStudents' %}?uId={{user.id}}&idC={{c.id}}">{{c.titleClass}}</a>
        {% endfor %}
      </div>
    </div>
  </li>
  
</ul>

{% endblock %}