SchoolProjectS6/PFES6/urls.py
from django.urls import path

from . import views
app_name = 'PFES6'
urlpatterns = [
    path('', views.index, name='index'),
    path('teacher', views.teacher_index, name="teacher"),
    path('profileT', views.profileT, name='profileT'),
    path('displayData', views.displayData, name='displayData'),
    path('updatingData', views.updatingData, name='updatingData'),
    path('addCourseSubject', views.addCourseSubject, name='addCourseSubject'),
    path('addCourse', views.addCourse, name='addCourse'),
    path('allCourses', views.allCourses, name='allCourses'),
    path('formUploadC', views.formUploadC, name='formUploadC'),
    path('addingCourse', views.addingCourse, name='addingCourse'),
    path('deleteCourse', views.deleteCourse, name='deleteCourse'),
    path('displayCourseDetails', views.displayCourseDetails,
         name='displayCourseDetails'),
    path('formUploadTD', views.formUploadTD, name='formUploadTD'),
    path('addingTD', views.addingTD, name='addingTD'),
    path('formUploadTP', views.formUploadTP, name='formUploadTP'),
    path('addingTP', views.addingTP, name='addingTP'),
    path('formUploadCorre', views.formUploadCorre, name='formUploadCorre'),
    path('addingCorr', views.addingCorr, name='addingCorr'),
    path('deleteCourseFile', views.deleteCourseFile, name='deleteCourseFile'),
    path('deleteTD', views.deleteTD, name='deleteTD'),
    path('deleteTP', views.deleteTP, name='deleteTP'),
    path('deleteCorr', views.deleteCorr, name='deleteCorr'),
    path('formUploadHW', views.formUploadHW, name='formUploadHW'),
    path('sendingHW', views.sendingHW, name='sendingHW'),
    path('displayAllStudents', views.displayAllStudents, name='displayAllStudents'),
    path('statistics', views.statistics, name='statistics'),
    path('student', views.student_index, name='student'),
    path('student/course', views.student_course, name='student_course'),
    path('student/join_course', views.student_join_course,
         name='student_join_course'),
    path('student/to_do', views.student_to_do, name='student_to_do'),
    path('student/profile', views.student_profile, name='student_profile'),
    path('student/edit_picture', views.student_picture, name='student_picture'),
    path('student/put_todo', views.student_put_todo, name='student_put_todo'),
    path('student/edit_profile', views.student_edit_profile,
         name='student_edit_profile'),
    path('student/delete_course', views.destroy,
         name='destroy'),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name='logout'),

]

SchoolProjectS6/SchoolProjectS6/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from  django.conf.urls.static import static


urlpatterns = [
    path('', include('PFES6.urls')),
    path('admin/', admin.site.urls),
    
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

SchoolProjectS6/SchoolProjectS6/templates/student/Join_Course.html
{% extends "student/base.html" %}
{% load static %}

{% block title %}
  <title>Join New Course</title>
{% endblock %}

{% block sidebar %}
<ul class="navbar-nav sidebar sidebar-light accordion" id="accordionSidebar">
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'PFES6:student' %}?userId={{user.id}}">
    <div class="sidebar-brand-icon">
      Online Class
    </div>
    <div class="sidebar-brand-text mx-3"></div>
  </a>
  <hr class="sidebar-divider my-0">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:student' %}?userId={{user.id}}">
      <i class="fas fa-book"></i>
      <span>My Courses</span></a>
  </li>
  <hr class="sidebar-divider">
  <div class="sidebar-heading">
    Actions
  </div>
  <li class="nav-item active">
    <a class="nav-link" href="{% url 'PFES6:student_join_course' %}?userId={{user.id}}">
      <i class="fas fa-plus-square"></i>
      <span>Join Course</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:student_to_do' %}?userId={{user.id}}">
      <i class="fas fa-clipboard-check"></i>
      <span>To do</span>
    </a>
  </li>
  <hr class="sidebar-divider">
  <div class="sidebar-heading">
    Settings
  </div>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:student_profile' %}?userId={{user.id}}">
      <i class="fas fa-user-edit"></i>
      <span>Edit Profile</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="javascript:void(0);" data-toggle="modal" data-target="#logoutModal">
      <i class="fas fa-sign-out-alt"></i>
      <span>Logout</span>
    </a>
  </li>
  <hr class="sidebar-divider">
  <div class="version" id="version-ruangadmin"></div>
</ul>
{% endblock %}

{% block content_block %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Join a New Course</h1>
</div>
<!-- Form Basic -->
<div class="card mb-4" style="margin: 4rem 10vw;">
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Join Course</h6>
  </div>
  <div class="card-body">
    <form method="POST" action="/student/join_course">
      {% csrf_token %}
      <input type="text" name="userId" value="{{user.id}}" hidden>
      <div class="form-group">
        {% if c is none and x is none %}
        <label for="validationServer01">Course Code</label>
        <input type="text" class="form-control" id="validationServer01"
        placeholder="Code" name="codeC" required>
        {% else %}
          {% if c%}
            <input type="text" class="form-control is-invalid" id="validationServer01"
            placeholder="Code" name="codeC" required>
            <div class="invalid-feedback">
              Please provide a valid code.
            </div>
          {% else %}
            <input type="text" class="form-control is-invalid" id="validationServer01"
            placeholder="Code" name="codeC" required>
            <div class="invalid-feedback">
              You already joined this course.
            </div>
          {% endif %}
        {% endif %}
      </div>
      <input type="submit" value="Join" class="btn btn-primary">
    </form>
  </div>
</div>
{% endblock %}

SchoolProjectS6/SchoolProjectS6/templates/student/course.html
{% extends "student/base.html" %}
{% load static %}

{% block title %}
  <title>Course - {{ class.titleClass }}</title>
{% endblock %}

{% block sidebar %}
  <ul class="navbar-nav sidebar sidebar-light accordion" id="accordionSidebar">
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'PFES6:student' %}?userId={{user.id}}">
      <div class="sidebar-brand-icon">
        Online Class
      </div>
      <div class="sidebar-brand-text mx-3"></div>
    </a>
    <hr class="sidebar-divider my-0">
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'PFES6:student' %}?userId={{user.id}}">
        <i class="fas fa-book"></i>
        <span>My Courses</span></a>
    </li>
    <hr class="sidebar-divider">
    <div class="sidebar-heading">
      Actions
    </div>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'PFES6:student_join_course' %}?userId={{user.id}}">
        <i class="fas fa-plus-square"></i>
        <span>Join Course</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'PFES6:student_to_do' %}?userId={{user.id}}">
        <i class="fas fa-clipboard-check"></i>
        <span>To do</span>
      </a>
    </li>
    <hr class="sidebar-divider">
    <div class="sidebar-heading">
      Settings
    </div>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'PFES6:student_profile' %}?userId={{user.id}}">
        <i class="fas fa-user-edit"></i>
        <span>Edit Profile</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="javascript:void(0);" data-toggle="modal" data-target="#logoutModal">
        <i class="fas fa-sign-out-alt"></i>
        <span>Logout</span>
      </a>
    </li>
    <hr class="sidebar-divider">
    <div class="version" id="version-ruangadmin"></div>
  </ul>
{% endblock %}

{% block content_block %}
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{ class.titleClass }}</h1>
    <h3 class="h5 mb-0 text-gray-800">Prof.{{ userT.prenom }} {{ userT.nom }}</h3>
  </div>

  <div class="row">
    <div class="col-lg-12 mb-4">
      <!-- Course Tables -->
      <div class="card">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Courses Files</h6>
        </div>  
        <div class="table-responsive">
          <table class="table align-items-center table-flush">
            <tbody>
              {% for c in course %}
              <tr>
                <td>{{c.course.titleClass}}</td>
                <td style="text-align:right"><a href="{{ c.courseFile.url }}" class="btn btn-sm btn-primary">Download</a></td>
              </tr>
              {% empty %}
              <tr>
                <td align="center" colspan="2">No course files yet !</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="card-footer"></div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12 mb-4">
      <!-- TD Tables -->
      <div class="card">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">TD Files</h6>
        </div>  
        <div class="table-responsive">
          <table class="table align-items-center table-flush">
            <tbody>
              {% for d in td %}
              <tr>
                <td>{{d.titleTd}}</td>
                <td style="text-align:right"><a href="{{ d.tdFile.url }}" class="btn btn-sm btn-primary">Download</a></td>
              </tr>
              {% empty %}
              <tr>
                <td align="center" colspan="5">No TD's yet !</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="card-footer"></div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12 mb-4">
      <!-- TP Tables -->
      <div class="card">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">TP Files</h6>
        </div>  
        <div class="table-responsive">
          <table class="table align-items-center table-flush">
            <tbody>
              {% for p in tp %}
              <tr>
                <td>{{p.titleTp}}</td>
                <td style="text-align:right"><a href="{{ p.tpFile.url }}" class="btn btn-sm btn-primary">Download</a></td>
              </tr>
              {% empty %}
              <tr>
                <td align="center" colspan="5">No TP's yet !</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="card-footer"></div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12 mb-4">
      <!-- TP Tables -->
      <div class="card" style="margin: auto;">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Corrections Files</h6>
        </div>  
        <div class="table-responsive">
          <table class="table align-items-center table-flush">
            <tbody>
              {% for co in corr %}
              <tr>
                <td>{{co.title}}</td>
                <td style="text-align:right"><a href="{{ co.corrFile.url }}" class="btn btn-sm btn-primary">Download</a></td>
              </tr>
              {% empty %}
              <tr>
                <td align="center" colspan="5">No Corrections yet !</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="card-footer"></div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12 mb-4">
      <!-- Todo Tables -->
      <div class="card">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">Homeworks</h6>
        </div>  
        <div class="table-responsive">
          <table class="table align-items-center table-flush">
            <tbody>
              {% for t in todo %}
              <tr>
                <td>{{ t.title }}</td>
                <td style="text-align:center"><a href="{{ t.TodoTFile.url }}" class="btn btn-sm btn-primary">Download</a></td>
                <td style="text-align:right"><a href="#" class="btn btn-sm btn-success">Put your report</a></td>
              </tr>
              {% empty %}
              <tr>
                <td align="center" colspan="5">No Homeworks yet !</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="card-footer"></div>
      </div>
    </div>
  </div>
  
{% endblock %}

SchoolProjectS6/SchoolProjectS6/templates/student/edit_profile.html
{% extends "student/base.html" %}
{% load static %}

{% block title %}
  <title>Profile</title>
{% endblock %}

{% block sidebar %}
<ul class="navbar-nav sidebar sidebar-light accordion" id="accordionSidebar">
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'PFES6:student' %}?userId={{user.id}}">
    <div class="sidebar-brand-icon">
      Online Class
    </div>
    <div class="sidebar-brand-text mx-3"></div>
  </a>
  <hr class="sidebar-divider my-0">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:student' %}?userId={{user.id}}">
      <i class="fas fa-book"></i>
      <span>My Courses</span></a>
  </li>
  <hr class="sidebar-divider">
  <div class="sidebar-heading">
    Actions
  </div>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:student_join_course' %}?userId={{user.id}}">
      <i class="fas fa-plus-square"></i>
      <span>Join Course</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:student_to_do' %}?userId={{user.id}}">
      <i class="fas fa-clipboard-check"></i>
      <span>To do</span>
    </a>
  </li>
  <hr class="sidebar-divider">
  <div class="sidebar-heading">
    Settings
  </div>
  <li class="nav-item active">
    <a class="nav-link" href="{% url 'PFES6:student_profile' %}?userId={{user.id}}">
      <i class="fas fa-user-edit"></i>
      <span>Edit Profile</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="javascript:void(0);" data-toggle="modal" data-target="#logoutModal">
      <i class="fas fa-sign-out-alt"></i>
      <span>Logout</span>
    </a>
  </li>
  <hr class="sidebar-divider">
  <div class="version" id="version-ruangadmin"></div>
</ul>
{% endblock %}

{% block content_block %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">My Profile</h1>
</div>

<div class="d-sm-flex align-items-center justify-content-between mb-4">

<div class="col">
<div class="row">
  <div class="col mb-3">
    <div class="card">
      <div class="card-body">
        <div class="e-profile">
          <div class="row">
            <div class="col-12 col-sm-auto mb-3">
              <div class="mx-auto" style="width: 140px;">
                  <img src="{{ user.picture.url }}" width="100%" height="140px" alt="">
                <!--div class="d-flex justify-content-center align-items-center rounded" style="height: 140px; background-color: rgb(233, 236, 239);">
                  <span style="color: rgb(166, 168, 170); font: bold 8pt Arial;">140x140</span>
                </div-->
              </div>
            </div>
            <div class="col d-flex flex-column flex-sm-row justify-content-between mb-3">
              <div class="text-center text-sm-left mb-2 mb-sm-0">
                <h4 class="pt-sm-2 pb-1 mb-0 text-nowrap">{{user.prenom}} {{user.nom}}</h4>
                <p class="mb-0">SMI</p>
                <div class="mt-2">
                  <form id="picup" method="POST" action="/student/edit_picture" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="text" name="userId" value="{{user.id}}" hidden>
                    <input type="file" id="picture_pick" name="picture" hidden>
                    <button class="btn btn-primary" id="picchange" type="button">
                      <i class="fa fa-fw fa-camera"></i>
                      <span>Change Picture</span>
                    </button>
                  </form>
                </div>
              </div>
            </div>
          </div>
          <div class="tab-content pt-3">
            <div class="tab-pane active">
              <form class="form" method="POST" action="/student/edit_profile">
                {% csrf_token %}
                <input type="text" name="userId" value="{{user.id}}" hidden>
                <div class="row">
                  <div class="col">
                    <div class="row">
                      <div class="col">
                        <div class="form-group">
                          <label>First Name</label>
                          <input class="form-control" type="text" name="prenom" value="{{user.prenom}}" required>
                        </div>
                      </div>
                      <div class="col">
                        <div class="form-group">
                          <label>Last Name</label>
                          <input class="form-control" type="text" name="nom" value="{{user.nom}}" required>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col">
                        <div class="form-group">
                          <label>Email</label>
                          <input class="form-control" type="text" name="email" value="{{user.email}}" readonly>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-12 col-sm-12 mb-3">
                    <div class="mb-2"><b>Change Password</b></div>

                    <!-- Current password -->
                    {% if p is none %}
                    <div class="row">
                      <div class="col">
                        <div class="form-group">
                          <label>Current Password</label>
                          <input class="form-control" name="oldpass" type="password">
                        </div>
                      </div>
                    </div>
                    {% else %}
                    <div class="row">
                      <div class="col">
                        <div class="form-group">
                          <label>Current Password</label>
                          <input class="form-control is-invalid" name="oldpass" type="password">
                          <div class="invalid-feedback">
                            Please provide the correct password.
                          </div>                  
                        </div>
                      </div>
                    </div>
                    {% endif %}
                    <!-- New Password -->
                    {% if np is none %}
                    <div class="row">
                      <div class="col">
                        <div class="form-group">
                          <label>New Password</label>
                          <input class="form-control" name="newpass" type="password">
                        </div>
                      </div>
                      <div class="col">
                        <div class="form-group">
                          <label>Confirm <span class="d-none d-xl-inline">Password</span></label>
                          <input class="form-control" name="newpass2" type="password"></div>
                      </div>
                    </div>
                    {% else %}
                    <div class="row">
                      <div class="col">
                        <div class="form-group">
                          <label>New Password</label>
                          <input class="form-control is-invalid" name="newpass" type="password">
                          <div class="invalid-feedback">
                            Passwords are not the same.
                          </div>                  
                        </div>
                      </div>
                      <div class="col">
                        <div class="form-group">
                          <label>Confirm <span class="d-none d-xl-inline">Password</span></label>
                          <input class="form-control is-invalid" name="newpass2" type="password"></div>
                      </div>
                    </div>
                    {% endif %}
                  </div>
                </div>
                <div class="row">
                  <div class="col d-flex justify-content-end">
                    <button class="btn btn-primary" type="submit">Save Changes</button>
                  </div>
                </div>
              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

</div>
{% endblock %}

SchoolProjectS6/SchoolProjectS6/templates/student/index.html
{% extends "student/base.html" %}
{% load static %}

{% block title %}
  <title>My Courses</title>
{% endblock %}

{% block sidebar %}
<ul class="navbar-nav sidebar sidebar-light accordion" id="accordionSidebar">
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'PFES6:student' %}?userId={{user.id}}">
    <div class="sidebar-brand-icon">
      Online Class
    </div>
    <div class="sidebar-brand-text mx-3"></div>
  </a>
  <hr class="sidebar-divider my-0">
  <li class="nav-item active">
    <a class="nav-link" href="{% url 'PFES6:student' %}?userId={{user.id}}">
      <i class="fas fa-book"></i>
      <span>My Courses</span></a>
  </li>
  <hr class="sidebar-divider">
  <div class="sidebar-heading">
    Actions
  </div>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:student_join_course' %}?userId={{user.id}}">
      <i class="fas fa-plus-square"></i>
      <span>Join Course</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:student_to_do' %}?userId={{user.id}}">
      <i class="fas fa-clipboard-check"></i>
      <span>To do</span>
    </a>
  </li>
  <hr class="sidebar-divider">
  <div class="sidebar-heading">
    Settings
  </div>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:student_profile' %}?userId={{user.id}}">
      <i class="fas fa-user-edit"></i>
      <span>Edit Profile</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="javascript:void(0);" data-toggle="modal" data-target="#logoutModal">
      <i class="fas fa-sign-out-alt"></i>
      <span>Logout</span>
    </a>
  </li>
  <hr class="sidebar-divider">
  <div class="version" id="version-ruangadmin"></div>
</ul>
{% endblock %}

{% block content_block %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">My Courses</h1>
</div>

<div class="row mb-3">

  <a  href="{% url 'PFES6:student_join_course' %}?userId={{user.id}}" class="col-xl-3 col-md-6 mb-4 text-gray-800">
    <div class="card index_card h-100">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div style="margin: 1rem auto;">
            <i class="fas fa-plus fa-5x"></i>
          </div>
        </div>
      </div>
    </div>
  </a>
  {% for c in join %}
  <a href="{% url 'PFES6:student_course' %}?userId={{user.id}}&courseId={{c.classId.id}}" class="col-xl-3 col-md-6 mb-4">
    <div class="card index_card h-100">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="h5 mb-0 font-weight-bold text-gray-800">{{c.classId.titleClass}}</div>
            <div class=" mb-1 text-muted">{{c.classId.level}}</div>
            <div class="mt-2 mb-0 text-muted text-xs">Prof.{{c.classId.userId.prenom}} {{c.classId.userId.nom}}</div>
            
            <form method="POST" action="/student/delete_course">
              {% csrf_token %}
              <input type="text" name="todelete" value="{{c.id}}" hidden>
              <input type="text" name="userId" value="{{user.id}}" hidden>
              <button class="mt-2 mb-0 text-xs leave-course" type="submit">Leave this course</button>
            </form>
          </div>
          <div class="col-auto" style="align-self: flex-start;">
            <img class="img-profile rounded-circle" src="{{ c.classId.userId.picture.url }}" width="58px" height="58px" alt="">
          </div>
        </div>
      </div>
    </div>
  </a>
  {% endfor %}
  </div>
  {% endblock %}

SchoolProjectS6/SchoolProjectS6/templates/student/to_do.html
{% extends "student/base.html" %}
{% load static %}

{% block title %}
  <title>To Do</title>
{% endblock %}

{% block sidebar %}
<ul class="navbar-nav sidebar sidebar-light accordion" id="accordionSidebar">
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'PFES6:student' %}?userId={{user.id}}">
    <div class="sidebar-brand-icon">
      Online Class
    </div>
    <div class="sidebar-brand-text mx-3"></div>
  </a>
  <hr class="sidebar-divider my-0">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:student' %}?userId={{user.id}}">
      <i class="fas fa-book"></i>
      <span>My Courses</span></a>
  </li>
  <hr class="sidebar-divider">
  <div class="sidebar-heading">
    Actions
  </div>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:student_join_course' %}?userId={{user.id}}">
      <i class="fas fa-plus-square"></i>
      <span>Join Course</span>
    </a>
  </li>
  <li class="nav-item active">
    <a class="nav-link" href="{% url 'PFES6:student_to_do' %}?userId={{user.id}}">
      <i class="fas fa-clipboard-check"></i>
      <span>To do</span>
    </a>
  </li>
  <hr class="sidebar-divider">
  <div class="sidebar-heading">
    Settings
  </div>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'PFES6:student_profile' %}?userId={{user.id}}">
      <i class="fas fa-user-edit"></i>
      <span>Edit Profile</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="javascript:void(0);" data-toggle="modal" data-target="#logoutModal">
      <i class="fas fa-sign-out-alt"></i>
      <span>Logout</span>
    </a>
  </li>
  <hr class="sidebar-divider">
  <div class="version" id="version-ruangadmin"></div>
</ul>
{% endblock %}

{% block content_block %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Reports List</h1>
</div>

<div class="row">
  <div class="col-lg-12 mb-4">
    <!-- Todo Tables -->
    <div class="card">
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">TP Files</h6>
      </div>  
      <div class="table-responsive">
        <table class="table align-items-center table-flush">
          <thead class="thead-light">
            <tr>
              <th></th>
              <th>Teacher</th>
              <th>Module</th>
              <th>Download</th>
              <th>Return</th>
            </tr>
          </thead>
          <tbody>
            {% for t in todo %}
              {% for j in join %}
                {% if t.course.id == j.classId.id %}
                  <tr>
                    <td>{{ t.title }}</td>
                    <td>Prof.{{ t.course.userId.prenom }} {{ t.course.userId.nom }}</td>
                    <td>{{ t.course.titleClass}}</td>
                    <td><a href="{{ t.TodoTFile.url }}" class="btn btn-sm btn-primary">Download</a></td>
                    <form id="todoup{{t.id}}" method="POST" action="/student/put_todo" enctype="multipart/form-data">
                      {% csrf_token %}
                      <input type="text" name="userId" value="{{user.id}}" hidden>
                      <input type="text" name="todoId" value="{{t.id}}" hidden>
                      <input type="file" id="todo_pick{{t.id}}" name="todo" hidden>
                      {% if not t.TodoSFile %}
                      <td><button id="todochange{{t.id}}" class="btn btn-sm btn-warning" type="button">Put your report</button></td>
                      {% else %}
                      <td><button id="todochange{{t.id}}" class="btn btn-sm btn-success" type="button" disabled>done</button></td>
                      {% endif %}
                    </form>
                  </tr>
                  <script>
                    document.querySelector("#todo_pick{{t.id}}").onchange = function() {
                      document.querySelector("#todoup{{t.id}}").submit();
                    };
                    document.querySelector('#todochange{{t.id}}').onclick = function(){
                      document.querySelector('#todo_pick{{t.id}}').click();
                    };
                  </script>
                {% endif %}
              {% endfor %}
            {% empty %}
            <tr>
              <td align="center" colspan="5">No Homeworks yet !</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="card-footer"></div>
    </div>
  </div>
</div>
{% endblock %}